import express from "express";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { createGraphTesterRouter } from "./routes/graphTesterRoutes.js";

// Production Vue build output. Generated by `npm --prefix src/graph-tester/client run build`.
const clientDistDirectory = fileURLToPath(new URL("./client/dist/", import.meta.url));
const clientIndexFile = fileURLToPath(new URL("./client/dist/index.html", import.meta.url));

export function createGraphTesterApp({ config, authStore }) {
  const app = express();
  const hasClientBuild = existsSync(clientIndexFile);

  app.disable("x-powered-by");
  app.use(express.json({ limit: "1mb" }));
  app.use((request, response, next) => {
    if (
      request.path.startsWith("/api/") ||
      request.path.startsWith("/auth/")
    ) {
      response.set("Cache-Control", "no-store");
    }

    next();
  });

  // API + OAuth routes always win over static assets.
  app.use(createGraphTesterRouter({ config, authStore }));

  if (hasClientBuild) {
    app.use(express.static(clientDistDirectory));
  }

  // SPA fallback: send the Vue index.html for non-API GET navigations so the
  // OAuth redirect to "/" (and any deep link) lands on the app. Written as a
  // path-less middleware to stay compatible with Express 5 routing.
  if (hasClientBuild) {
    app.use((request, response, next) => {
      if (
        request.method !== "GET" ||
        request.path.startsWith("/api/") ||
        request.path.startsWith("/auth/")
      ) {
        next();
        return;
      }

      response.sendFile(clientIndexFile);
    });
  }

  app.use((request, response) => {
    if (!hasClientBuild && request.method === "GET") {
      response
        .status(503)
        .type("text/plain")
        .send("Graph Tester client is not built. Run npm run graph-tester:client:build.");
      return;
    }

    response.status(404).type("text/plain").send("Graph tester route not found.");
  });

  app.use((error, request, response, next) => {
    response.status(error.statusCode || 500).json({
      ok: false,
      error: error.message || "Unexpected Graph tester server error.",
    });
  });

  return app;
}
