const GRAPH_SELECT_FIELDS = {
  "user:getMe": [
    "id",
    "displayName",
    "userPrincipalName",
    "mail",
    "jobTitle",
    "department",
    "officeLocation",
    "mobilePhone",
    "businessPhones",
    "accountEnabled",
    "userType",
  ],
  "user:listUsers": [
    "id",
    "displayName",
    "userPrincipalName",
    "mail",
    "jobTitle",
    "department",
    "officeLocation",
    "mobilePhone",
    "businessPhones",
    "accountEnabled",
    "userType",
  ],
  "user:searchUsers": [
    "id",
    "displayName",
    "userPrincipalName",
    "mail",
    "jobTitle",
    "department",
    "officeLocation",
    "mobilePhone",
    "businessPhones",
    "accountEnabled",
    "userType",
  ],
  "user:getUser": [
    "id",
    "displayName",
    "userPrincipalName",
    "mail",
    "jobTitle",
    "department",
    "officeLocation",
    "mobilePhone",
    "businessPhones",
    "accountEnabled",
    "userType",
  ],
  "user:getUserManager": [
    "id",
    "displayName",
    "userPrincipalName",
    "mail",
    "jobTitle",
    "department",
    "officeLocation",
  ],
  "user:listUserDirectReports": [
    "id",
    "displayName",
    "userPrincipalName",
    "mail",
    "jobTitle",
    "department",
    "officeLocation",
  ],
  "user:listUserJoinedTeams": [
    "id",
    "displayName",
    "description",
    "webUrl",
    "isArchived",
    "visibility",
    "createdDateTime",
  ],
  "user:listUserMemberOf": [
    "id",
    "displayName",
    "mail",
    "securityEnabled",
    "groupTypes",
  ],
  "calendar:listMyCalendars": [
    "id",
    "name",
    "color",
    "changeKey",
    "canShare",
    "canViewPrivateItems",
    "canEdit",
    "isDefaultCalendar",
    "isRemovable",
    "owner",
  ],
  "calendar:getCalendar": [
    "id",
    "name",
    "color",
    "changeKey",
    "canShare",
    "canViewPrivateItems",
    "canEdit",
    "isDefaultCalendar",
    "isRemovable",
    "owner",
  ],
  "calendar:listEvents": [
    "id",
    "subject",
    "bodyPreview",
    "organizer",
    "attendees",
    "start",
    "end",
    "location",
    "isAllDay",
    "isCancelled",
    "isOrganizer",
    "responseStatus",
    "webLink",
    "onlineMeeting",
    "createdDateTime",
    "lastModifiedDateTime",
  ],
  "calendar:listMyCalendarEvents": [
    "id",
    "subject",
    "bodyPreview",
    "organizer",
    "attendees",
    "start",
    "end",
    "location",
    "isAllDay",
    "isCancelled",
    "isOrganizer",
    "responseStatus",
    "webLink",
    "onlineMeeting",
    "createdDateTime",
    "lastModifiedDateTime",
  ],
  "calendar:getEvent": [
    "id",
    "subject",
    "bodyPreview",
    "organizer",
    "attendees",
    "start",
    "end",
    "location",
    "isAllDay",
    "isCancelled",
    "isOrganizer",
    "responseStatus",
    "webLink",
    "onlineMeeting",
    "createdDateTime",
    "lastModifiedDateTime",
  ],
  "calendar:getMyCalendarView": [
    "id",
    "subject",
    "bodyPreview",
    "organizer",
    "attendees",
    "start",
    "end",
    "location",
    "isAllDay",
    "isCancelled",
    "isOrganizer",
    "responseStatus",
    "webLink",
    "onlineMeeting",
    "createdDateTime",
    "lastModifiedDateTime",
  ],
  "calendar:listSharedCalendarEvents": [
    "id",
    "subject",
    "bodyPreview",
    "organizer",
    "attendees",
    "start",
    "end",
    "location",
    "isAllDay",
    "isCancelled",
    "isOrganizer",
    "responseStatus",
    "webLink",
    "onlineMeeting",
    "createdDateTime",
    "lastModifiedDateTime",
  ],
  "calendar:getSharedCalendarView": [
    "id",
    "subject",
    "bodyPreview",
    "organizer",
    "attendees",
    "start",
    "end",
    "location",
    "isAllDay",
    "isCancelled",
    "isOrganizer",
    "responseStatus",
    "webLink",
    "onlineMeeting",
    "createdDateTime",
    "lastModifiedDateTime",
  ],
  "calendar:listCalendarEvents": [
    "id",
    "subject",
    "bodyPreview",
    "organizer",
    "attendees",
    "start",
    "end",
    "location",
    "isAllDay",
    "isCancelled",
    "isOrganizer",
    "responseStatus",
    "webLink",
    "onlineMeeting",
    "createdDateTime",
    "lastModifiedDateTime",
  ],
  "calendar:listEventInstances": [
    "id",
    "subject",
    "bodyPreview",
    "organizer",
    "attendees",
    "start",
    "end",
    "location",
    "isAllDay",
    "isCancelled",
    "isOrganizer",
    "responseStatus",
    "webLink",
    "onlineMeeting",
    "createdDateTime",
    "lastModifiedDateTime",
  ],
  "calendar:listEventAttachments": [
    "id",
    "name",
    "contentType",
    "size",
    "isInline",
    "lastModifiedDateTime",
  ],
  "calendar:getEventAttachment": [
    "id",
    "name",
    "contentType",
    "size",
    "isInline",
    "lastModifiedDateTime",
  ],
  "mail:listMessages": [
    "id",
    "subject",
    "from",
    "sender",
    "toRecipients",
    "ccRecipients",
    "receivedDateTime",
    "sentDateTime",
    "bodyPreview",
    "isRead",
    "hasAttachments",
    "importance",
    "conversationId",
    "webLink",
  ],
  "mail:listInboxMessages": [
    "id",
    "subject",
    "from",
    "sender",
    "toRecipients",
    "ccRecipients",
    "receivedDateTime",
    "sentDateTime",
    "bodyPreview",
    "isRead",
    "hasAttachments",
    "importance",
    "conversationId",
    "webLink",
  ],
  "mail:getMessage": [
    "id",
    "subject",
    "body",
    "bodyPreview",
    "uniqueBody",
    "from",
    "sender",
    "toRecipients",
    "ccRecipients",
    "bccRecipients",
    "replyTo",
    "receivedDateTime",
    "sentDateTime",
    "createdDateTime",
    "lastModifiedDateTime",
    "hasAttachments",
    "importance",
    "inferenceClassification",
    "isRead",
    "isDraft",
    "internetMessageId",
    "internetMessageHeaders",
    "conversationId",
    "parentFolderId",
    "categories",
    "flag",
    "webLink",
  ],
  "mail:listMessagesInFolder": [
    "id",
    "subject",
    "from",
    "sender",
    "toRecipients",
    "ccRecipients",
    "receivedDateTime",
    "sentDateTime",
    "bodyPreview",
    "isRead",
    "hasAttachments",
    "importance",
    "conversationId",
    "webLink",
  ],
  "mail:listUnreadMessages": [
    "id",
    "subject",
    "from",
    "sender",
    "toRecipients",
    "ccRecipients",
    "receivedDateTime",
    "sentDateTime",
    "bodyPreview",
    "isRead",
    "hasAttachments",
    "importance",
    "conversationId",
    "webLink",
  ],
  "mail:listAllMessages": [
    "id",
    "subject",
    "from",
    "sender",
    "toRecipients",
    "ccRecipients",
    "receivedDateTime",
    "sentDateTime",
    "bodyPreview",
    "isRead",
    "hasAttachments",
    "importance",
    "conversationId",
    "webLink",
  ],
  "mail:searchMyMessages": [
    "id",
    "subject",
    "from",
    "sender",
    "toRecipients",
    "ccRecipients",
    "receivedDateTime",
    "sentDateTime",
    "bodyPreview",
    "isRead",
    "hasAttachments",
    "importance",
    "conversationId",
    "webLink",
  ],
  "mail:listSharedMailboxMessages": [
    "id",
    "subject",
    "from",
    "sender",
    "toRecipients",
    "ccRecipients",
    "receivedDateTime",
    "sentDateTime",
    "bodyPreview",
    "isRead",
    "hasAttachments",
    "importance",
    "conversationId",
    "webLink",
  ],
  "mail:listSharedInboxMessages": [
    "id",
    "subject",
    "from",
    "sender",
    "toRecipients",
    "ccRecipients",
    "receivedDateTime",
    "sentDateTime",
    "bodyPreview",
    "isRead",
    "hasAttachments",
    "importance",
    "conversationId",
    "webLink",
  ],
  "mail:deltaMessages": [
    "id",
    "subject",
    "from",
    "sender",
    "toRecipients",
    "ccRecipients",
    "receivedDateTime",
    "sentDateTime",
    "bodyPreview",
    "isRead",
    "hasAttachments",
    "importance",
    "conversationId",
    "webLink",
  ],
  "mail:listMailFolders": [
    "id",
    "displayName",
    "parentFolderId",
    "childFolderCount",
    "totalItemCount",
    "unreadItemCount",
  ],
  "mail:getMailFolder": [
    "id",
    "displayName",
    "parentFolderId",
    "childFolderCount",
    "totalItemCount",
    "unreadItemCount",
  ],
  "mail:listChildFolders": [
    "id",
    "displayName",
    "parentFolderId",
    "childFolderCount",
    "totalItemCount",
    "unreadItemCount",
  ],
  "mail:listAttachments": [
    "id",
    "name",
    "contentType",
    "size",
    "isInline",
    "lastModifiedDateTime",
  ],
  "mail:getAttachment": [
    "id",
    "name",
    "contentType",
    "size",
    "isInline",
    "lastModifiedDateTime",
  ],
  "mail:listMessageRules": [
    "id",
    "displayName",
    "sequence",
    "isEnabled",
    "hasError",
    "isReadOnly",
    "conditions",
    "actions",
    "exceptions",
  ],
  "mail:getMessageRule": [
    "id",
    "displayName",
    "sequence",
    "isEnabled",
    "hasError",
    "isReadOnly",
    "conditions",
    "actions",
    "exceptions",
  ],
  "mail:listOutlookCategories": [
    "id",
    "displayName",
    "color",
  ],
  "mailboxSettings:getMyMailboxSettings": [
    "automaticRepliesSetting",
    "dateFormat",
    "delegateMeetingMessageDeliveryOptions",
    "language",
    "locale",
    "timeFormat",
    "timeZone",
    "workingHours",
    "userPurpose",
  ],
  "teamsChat:listMyChats": [
    "id",
    "chatType",
    "topic",
    "createdDateTime",
    "lastUpdatedDateTime",
    "webUrl",
    "tenantId",
    "onlineMeetingInfo",
    "viewpoint",
  ],
  "teamsChat:getChat": [
    "id",
    "chatType",
    "topic",
    "createdDateTime",
    "lastUpdatedDateTime",
    "webUrl",
    "tenantId",
    "onlineMeetingInfo",
    "viewpoint",
  ],
  "teamsChat:listChatMembers": [
    "id",
    "displayName",
    "roles",
    "visibleHistoryStartDateTime",
    "userId",
    "email",
    "tenantId",
  ],
  "teamsChat:getChatMember": [
    "id",
    "displayName",
    "roles",
    "visibleHistoryStartDateTime",
    "userId",
    "email",
    "tenantId",
  ],
  "teamsChat:listChatMessages": [
    "id",
    "replyToId",
    "etag",
    "messageType",
    "createdDateTime",
    "lastModifiedDateTime",
    "lastEditedDateTime",
    "deletedDateTime",
    "subject",
    "summary",
    "chatId",
    "importance",
    "locale",
    "webUrl",
    "from",
    "body",
    "attachments",
    "mentions",
    "reactions",
  ],
  "teamsChat:getChatMessage": [
    "id",
    "replyToId",
    "etag",
    "messageType",
    "createdDateTime",
    "lastModifiedDateTime",
    "lastEditedDateTime",
    "deletedDateTime",
    "subject",
    "summary",
    "chatId",
    "importance",
    "locale",
    "webUrl",
    "from",
    "body",
    "attachments",
    "mentions",
    "reactions",
  ],
  "teamsChat:listChatMessageHostedContents": [
    "id",
    "contentBytes",
    "contentType",
  ],
  "teamsChat:getChatMessageHostedContent": [
    "id",
    "contentBytes",
    "contentType",
  ],
  "teamsChat:listChatTabs": [
    "id",
    "displayName",
    "webUrl",
    "configuration",
    "teamsApp",
  ],
  "teamsChat:listChatInstalledApps": [
    "id",
    "teamsApp",
    "teamsAppDefinition",
  ],
  "teamsChannel:listChannels": [
    "id",
    "displayName",
    "description",
    "email",
    "webUrl",
    "createdDateTime",
    "membershipType",
    "isArchived",
    "tenantId",
    "summary",
  ],
  "teamsChannel:getChannel": [
    "id",
    "displayName",
    "description",
    "email",
    "webUrl",
    "createdDateTime",
    "membershipType",
    "isArchived",
    "tenantId",
    "summary",
  ],
  "teamsChannel:listChannelMessages": [
    "id",
    "replyToId",
    "etag",
    "messageType",
    "createdDateTime",
    "lastModifiedDateTime",
    "lastEditedDateTime",
    "deletedDateTime",
    "subject",
    "summary",
    "chatId",
    "importance",
    "locale",
    "webUrl",
    "from",
    "body",
    "attachments",
    "mentions",
    "reactions",
  ],
  "teamsChannel:getChannelMessage": [
    "id",
    "replyToId",
    "etag",
    "messageType",
    "createdDateTime",
    "lastModifiedDateTime",
    "lastEditedDateTime",
    "deletedDateTime",
    "subject",
    "summary",
    "chatId",
    "importance",
    "locale",
    "webUrl",
    "from",
    "body",
    "attachments",
    "mentions",
    "reactions",
  ],
  "people:listRelevantPeople": [
    "id",
    "displayName",
    "givenName",
    "surname",
    "userPrincipalName",
    "scoredEmailAddresses",
    "phones",
    "jobTitle",
    "companyName",
    "department",
    "officeLocation",
    "personType",
    "isFavorite",
  ],
  "people:searchPeople": [
    "id",
    "displayName",
    "givenName",
    "surname",
    "userPrincipalName",
    "scoredEmailAddresses",
    "phones",
    "jobTitle",
    "companyName",
    "department",
    "officeLocation",
    "personType",
    "isFavorite",
  ],
  "serviceHealth:listServiceHealthOverviews": ["id", "service", "status"],
  "serviceHealth:getServiceHealthOverview": ["id", "service", "status"],
  "serviceHealth:listServiceHealthIssues": ["id", "title", "service", "feature", "featureGroup", "classification", "origin", "status", "impactDescription", "startDateTime", "endDateTime", "lastModifiedDateTime", "isResolved"],
  "serviceHealth:getServiceHealthIssue": ["id", "title", "service", "feature", "featureGroup", "classification", "origin", "status", "impactDescription", "startDateTime", "endDateTime", "lastModifiedDateTime", "isResolved"],
  "directory:listApplications": ["id", "appId", "displayName", "description", "signInAudience", "createdDateTime", "web", "spa", "publicClient", "appRoles"],
  "directory:getApplication": ["id", "appId", "displayName", "description", "signInAudience", "createdDateTime", "requiredResourceAccess", "web", "spa", "publicClient", "appRoles"],
  "directory:listServicePrincipals": ["id", "appId", "displayName", "servicePrincipalType", "accountEnabled", "appOwnerOrganizationId", "createdDateTime", "tags"],
  "directory:getServicePrincipal": ["id", "appId", "displayName", "servicePrincipalType", "accountEnabled", "appOwnerOrganizationId", "createdDateTime", "tags", "appRoles", "oauth2PermissionScopes"],
  "directory:listDevices": ["id", "displayName", "deviceId", "accountEnabled", "operatingSystem", "operatingSystemVersion", "trustType", "approximateLastSignInDateTime", "isCompliant", "isManaged", "createdDateTime"],
  "directory:getDevice": ["id", "displayName", "deviceId", "accountEnabled", "operatingSystem", "operatingSystemVersion", "trustType", "approximateLastSignInDateTime", "isCompliant", "isManaged", "createdDateTime"],
  "directory:listDirectoryRoles": ["id", "displayName", "description", "roleTemplateId"],
  "directory:getDirectoryRole": ["id", "displayName", "description", "roleTemplateId"],
  "directory:listDirectoryRoleMembers": ["id", "displayName", "givenName", "surname", "userPrincipalName", "mail", "jobTitle", "officeLocation", "businessPhones", "mobilePhone"],
  "directory:getOrganization": ["id", "displayName", "verifiedDomains", "assignedPlans", "provisionedPlans", "businessPhones", "city", "country", "countryLetterCode"],
  "directory:listSubscribedSkus": ["id", "skuId", "skuPartNumber", "capabilityStatus", "consumedUnits", "prepaidUnits", "servicePlans", "appliesTo"],
  "directory:listDomains": ["id", "isVerified", "isDefault", "isInitial", "isRoot", "isAdminManaged", "supportedServices", "state"],
  "directory:getDomain": ["id", "isVerified", "isDefault", "isInitial", "isRoot", "isAdminManaged", "supportedServices", "state"],
  "groups:listGroups": ["id", "displayName", "description", "mail", "mailNickname", "mailEnabled", "securityEnabled", "groupTypes", "visibility", "createdDateTime", "renewedDateTime"],
  "groups:getGroup": ["id", "displayName", "description", "mail", "mailNickname", "mailEnabled", "securityEnabled", "groupTypes", "visibility", "createdDateTime", "renewedDateTime"],
  "groups:listGroupMembers": ["id", "displayName", "givenName", "surname", "userPrincipalName", "mail", "jobTitle", "officeLocation", "businessPhones", "mobilePhone"],
  "groups:listGroupTransitiveMembers": ["id", "displayName", "givenName", "surname", "userPrincipalName", "mail", "jobTitle", "officeLocation", "businessPhones", "mobilePhone"],
  "groups:listGroupOwners": ["id", "displayName", "givenName", "surname", "userPrincipalName", "mail", "jobTitle", "officeLocation", "businessPhones", "mobilePhone"],
  "tasks:listTodoLists": ["id", "displayName", "isOwner", "isShared", "wellknownListName"],
  "tasks:getTodoList": ["id", "displayName", "isOwner", "isShared", "wellknownListName"],
  "tasks:listTasks": ["id", "title", "status", "importance", "isReminderOn", "createdDateTime", "lastModifiedDateTime", "dueDateTime", "reminderDateTime", "completedDateTime", "categories"],
  "tasks:getTask": ["id", "title", "status", "importance", "isReminderOn", "createdDateTime", "lastModifiedDateTime", "dueDateTime", "reminderDateTime", "completedDateTime", "body", "categories", "recurrence"],
  "onenote:listNotebooks": ["id", "displayName", "createdDateTime", "lastModifiedDateTime", "isDefault", "userRole", "isShared"],
  "onenote:getNotebook": ["id", "displayName", "createdDateTime", "lastModifiedDateTime", "isDefault", "userRole", "isShared", "links", "sectionsUrl"],
  "onenote:listSections": ["id", "displayName", "createdDateTime", "lastModifiedDateTime", "isDefault"],
  "onenote:getSection": ["id", "displayName", "createdDateTime", "lastModifiedDateTime", "isDefault", "links", "pagesUrl", "parentNotebook"],
  "onenote:listPages": ["id", "title", "createdDateTime", "lastModifiedDateTime", "level", "order"],
  "onenote:getPage": ["id", "title", "createdDateTime", "lastModifiedDateTime", "links", "level", "order", "parentSection", "contentUrl"],
  "sites:searchSites": ["id", "name", "displayName", "webUrl", "description", "createdDateTime", "lastModifiedDateTime", "siteCollection", "sharepointIds"],
  "sites:getSite": ["id", "name", "displayName", "webUrl", "description", "createdDateTime", "lastModifiedDateTime", "siteCollection", "root", "sharepointIds"],
  "sites:getRootSite": ["id", "name", "displayName", "webUrl", "description", "createdDateTime", "siteCollection", "root"],
  "sites:listSubsites": ["id", "name", "displayName", "webUrl", "description", "createdDateTime"],
  "sites:listSiteDrives": ["id", "driveType", "name", "owner", "quota", "webUrl", "createdDateTime", "lastModifiedDateTime"],
  "sites:listSiteLists": ["id", "displayName", "name", "webUrl", "createdDateTime", "lastModifiedDateTime", "list"],
  "sites:getSiteList": ["id", "displayName", "name", "webUrl", "createdDateTime", "lastModifiedDateTime", "list"],
  "sites:listListItems": ["id", "webUrl", "createdDateTime", "lastModifiedDateTime", "contentType"],
  "sites:getListItem": ["id", "webUrl", "createdDateTime", "lastModifiedDateTime", "contentType"],
  "sites:listSitePages": ["id", "name", "title", "webUrl", "createdDateTime", "lastModifiedDateTime", "publishingState"],
  "files:getMyDrive": ["id", "driveType", "name", "owner", "quota", "webUrl", "createdDateTime", "lastModifiedDateTime"],
  "files:getDrive": ["id", "driveType", "name", "owner", "quota", "webUrl", "createdDateTime", "lastModifiedDateTime"],
  "files:listRootChildren": ["id", "name", "webUrl", "size", "createdDateTime", "lastModifiedDateTime", "createdBy", "lastModifiedBy", "parentReference", "file", "folder"],
  "files:getDriveItem": ["id", "name", "webUrl", "size", "createdDateTime", "lastModifiedDateTime", "createdBy", "lastModifiedBy", "parentReference", "file", "folder", "package", "shared"],
  "files:listItemChildren": ["id", "name", "webUrl", "size", "createdDateTime", "lastModifiedDateTime", "createdBy", "lastModifiedBy", "parentReference", "file", "folder"],
  "files:searchDriveItems": ["id", "name", "webUrl", "size", "createdDateTime", "lastModifiedDateTime", "createdBy", "parentReference", "file", "folder"],
  "files:listRecentFiles": ["id", "name", "webUrl", "size", "createdDateTime", "lastModifiedDateTime", "createdBy", "parentReference", "file"],
  "files:listSharedWithMe": ["id", "name", "webUrl", "size", "createdDateTime", "lastModifiedDateTime", "createdBy", "parentReference", "file", "shared"],
  "files:listAppFolderChildren": ["id", "name", "webUrl", "size", "createdDateTime", "lastModifiedDateTime", "file", "folder"],
  "contacts:listContacts": ["id", "displayName", "givenName", "surname", "emailAddresses", "companyName", "department", "jobTitle", "businessPhones", "mobilePhone", "officeLocation"],
  "contacts:getContact": ["id", "displayName", "givenName", "surname", "emailAddresses", "companyName", "department", "jobTitle", "businessPhones", "mobilePhone", "officeLocation", "createdDateTime", "lastModifiedDateTime"],
  "contacts:listUserContacts": ["id", "displayName", "givenName", "surname", "emailAddresses", "companyName", "department", "jobTitle", "businessPhones", "mobilePhone"],
  "contacts:getUserContact": ["id", "displayName", "givenName", "surname", "emailAddresses", "companyName", "department", "jobTitle", "businessPhones", "mobilePhone"],
  "contacts:listContactFolders": ["id", "displayName", "parentFolderId", "childFolderCount"],
  "contacts:getContactFolder": ["id", "displayName", "parentFolderId", "childFolderCount"],
  "contacts:listContactsInFolder": ["id", "displayName", "givenName", "surname", "emailAddresses", "companyName", "jobTitle", "businessPhones", "mobilePhone"],
  "calendarShared:getSharedCalendarEvent": ["id", "subject", "bodyPreview", "organizer", "attendees", "start", "end", "location", "isAllDay", "isCancelled", "isOrganizer", "responseStatus", "webLink", "onlineMeeting", "createdDateTime", "lastModifiedDateTime"],
  "mailShared:getSharedMailboxMessage": ["id", "subject", "from", "sender", "toRecipients", "ccRecipients", "receivedDateTime", "sentDateTime", "bodyPreview", "isRead", "hasAttachments", "importance", "conversationId", "webLink", "parentFolderId"],
  "mailShared:listSharedMailboxFolders": ["id", "displayName", "parentFolderId", "childFolderCount", "totalItemCount", "unreadItemCount"],
  "profile:listProfileNames": ["id", "displayName", "first", "last", "middle", "nickname", "suffix", "title"],
  "profile:listProfileEmails": ["id", "address", "displayName", "type"],
  "profile:listProfilePhones": ["id", "displayName", "number", "type"],
  "profile:listProfilePositions": ["id", "displayName", "detail", "isCurrent"],
  "profile:listProfileSkills": ["id", "displayName", "proficiency"],
};

const LABEL_OVERRIDES = {
  id: "ID",
  webUrl: "Web URL",
  userId: "User ID",
  tenantId: "Tenant ID",
  chatId: "Chat ID",
  etag: "ETag",
  ccRecipients: "CC recipients",
  bccRecipients: "BCC recipients",
  toRecipients: "To recipients",
  replyTo: "Reply-to",
  internetMessageId: "Internet message ID",
  parentFolderId: "Parent folder ID",
  userPrincipalName: "User principal name",
  bodyPreview: "Body preview",
  uniqueBody: "Unique body",
  mobilePhone: "Mobile phone",
  businessPhones: "Business phones",
  officeLocation: "Office location",
  accountEnabled: "Account enabled",
  userType: "User type",
  canShare: "Can share",
  canViewPrivateItems: "Can view private items",
  canEdit: "Can edit",
  isDefaultCalendar: "Default calendar",
  isRemovable: "Removable",
  isAllDay: "All day",
  isCancelled: "Cancelled",
  isOrganizer: "Organizer",
  responseStatus: "Response status",
  onlineMeeting: "Online meeting",
  onlineMeetingInfo: "Online meeting info",
  createdDateTime: "Created",
  lastModifiedDateTime: "Last modified",
  lastUpdatedDateTime: "Last updated",
  lastEditedDateTime: "Last edited",
  deletedDateTime: "Deleted",
  contentType: "Content type",
  contentBytes: "Content bytes",
  isInline: "Inline",
  isRead: "Read",
  hasAttachments: "Has attachments",
  childFolderCount: "Child folder count",
  totalItemCount: "Total item count",
  unreadItemCount: "Unread item count",
  isEnabled: "Enabled",
  hasError: "Has error",
  isReadOnly: "Read-only",
  automaticRepliesSetting: "Automatic replies",
  delegateMeetingMessageDeliveryOptions: "Delegate meeting delivery",
  timeFormat: "Time format",
  timeZone: "Time zone",
  userPurpose: "User purpose",
  visibleHistoryStartDateTime: "Visible history start",
  replyToId: "Reply-to ID",
  messageType: "Message type",
  teamsApp: "Teams app",
  teamsAppDefinition: "Teams app definition",
  membershipType: "Membership type",
  isArchived: "Archived",
  givenName: "Given name",
  surname: "Surname",
  scoredEmailAddresses: "Scored email addresses",
  companyName: "Company name",
  personType: "Person type",
  isFavorite: "Favorite",
  appId: "App ID",
  skuId: "SKU ID",
  skuPartNumber: "SKU part number",
  capabilityStatus: "Capability status",
  consumedUnits: "Consumed units",
  prepaidUnits: "Prepaid units",
  servicePlans: "Service plans",
  appliesTo: "Applies to",
  roleTemplateId: "Role template ID",
  servicePrincipalType: "Service principal type",
  appOwnerOrganizationId: "App owner org ID",
  oauth2PermissionScopes: "OAuth2 scopes",
  requiredResourceAccess: "Required resource access",
  deviceId: "Device ID",
  trustType: "Trust type",
  approximateLastSignInDateTime: "Approx. last sign-in",
  isCompliant: "Compliant",
  isManaged: "Managed",
  countryLetterCode: "Country code",
  verifiedDomains: "Verified domains",
  assignedPlans: "Assigned plans",
  provisionedPlans: "Provisioned plans",
  renewedDateTime: "Renewed",
  mailNickname: "Mail nickname",
  securityEnabled: "Security enabled",
  mailEnabled: "Mail enabled",
  groupTypes: "Group types",
  wellknownListName: "Well-known list name",
  isReminderOn: "Reminder on",
  dueDateTime: "Due",
  reminderDateTime: "Reminder",
  completedDateTime: "Completed",
  isShared: "Shared",
  isDefault: "Default",
  isOwner: "Owner",
  userRole: "User role",
  sectionsUrl: "Sections URL",
  pagesUrl: "Pages URL",
  parentNotebook: "Parent notebook",
  parentSection: "Parent section",
  contentUrl: "Content URL",
  siteCollection: "Site collection",
  sharepointIds: "SharePoint IDs",
  publishingState: "Publishing state",
  driveType: "Drive type",
  lastModifiedBy: "Last modified by",
  parentReference: "Parent reference",
  emailAddresses: "Email addresses",
  childFolderCount: "Child folder count",
  featureGroup: "Feature group",
  classification: "Classification",
  impactDescription: "Impact description",
  isResolved: "Resolved",
  isInitial: "Initial",
  isRoot: "Root",
  isAdminManaged: "Admin managed",
  supportedServices: "Supported services",
  signInAudience: "Sign-in audience",
  publicClient: "Public client",
  appRoles: "App roles",
};

export function getGraphSelectMetadata(service, functionName) {
  const values = GRAPH_SELECT_FIELDS[`${service}:${functionName}`];

  if (!Array.isArray(values) || values.length === 0) {
    return null;
  }

  return {
    values: [...values],
    options: values.map((value) => ({
      value,
      label: toFriendlyLabel(value),
    })),
  };
}

function toFriendlyLabel(value) {
  const override = LABEL_OVERRIDES[value];

  if (override) {
    return override;
  }

  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/_/g, " ")
    .replace(/\bId\b/g, "ID")
    .replace(/\bUrl\b/g, "URL")
    .replace(/\bHtml\b/g, "HTML")
    .replace(/\bMime\b/g, "MIME")
    .replace(/^./, (character) => character.toUpperCase());
}
